#!/bin/bash

# Script: generate-assembly.sh
# Description: This script generates the assembly code for the C file specified in the $CFILE variable.
#
# Author: Destiny Saturday (DestinedCodes)
# Date: 2023-02-16

gcc -S $CFILE

