#!/bin/bash

# Script: cisfun.sh
# Description: This script compiles the C file specified in the $CFILE variable and creates an executable named "cisfun".
#
# Author: Destiny Saturday (DestinedCodes)
# Date: 2023-02-16

gcc $CFILE -o cisfun

